services:
  db:
    container_name: 'postgres'
    image: 'postgres:14.1-alpine'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped

volumes:
  postgres_data:
