const TipoImpressaoEnum = {
  UM_DOCUMENTO_PARA_MUITOS_USUARIOS: 'UM_DOCUMENTO_PARA_MUITOS_USUARIOS',
  UM_DOCUMENTO_PARA_UM_USUARIO: 'UM_DOCUMENTO_PARA_UM_USUARIO',
};

export default TipoImpressaoEnum;
